sudo: false
language: elixir
elixir:
  - 1.0.5
  - 1.1.1
otp_release:
  - 17.4
  - 18.0
matrix:
  exclude:
  - elixir: 1.0.5
    otp_release: 17.4
env:
  - MIX_ENV=all
notifications:
  email:
    - paulschoenfelder@gmail.com
